"""Adicionar column

Revision ID: 1196fb77f47c
Revises: 5d8b0a5ba965
Create Date: 2024-04-09 16:39:12.877359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1196fb77f47c'
down_revision = '5d8b0a5ba965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('a_fazer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('serial_number', type_='unique')
        batch_op.create_unique_constraint('serial_number', ['serial_number'])
        batch_op.drop_column('unique_serial_number_constraint')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('a_fazer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_serial_number_constraint', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('serial_numer', type_='unique')
        batch_op.create_unique_constraint('serial_number', ['unique_serial_number_constraint'])
        batch_op.drop_column('serial_number')

    # ### end Alembic commands ###
