"""empty message

Revision ID: 12085c554a0c
Revises: 81fb0a36161a
Create Date: 2024-06-13 18:21:15.819182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12085c554a0c'
down_revision = '81fb0a36161a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=True),
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordem_producao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('roteiro_id', type_='foreignkey')
        batch_op.drop_column('roteiro_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roteiro_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'access_point', ['roteiro_id'], ['id'])

    op.drop_table('serial')
    # ### end Alembic commands ###
