"""add ordem_id to TraceSerial

Revision ID: 160927c9cfdf
Revises: 5f903c4ed258
Create Date: 2024-06-14 09:47:46.413935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160927c9cfdf'
down_revision = '5f903c4ed258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trace_serial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordem_id', sa.Integer(), nullable=False))
        # batch_op.create_foreign_key(None, 'ordem_producao', ['ordem_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trace_serial', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ordem_id')

    # ### end Alembic commands ###
