"""empty message

Revision ID: 3733b7119f7c
Revises: af6c7295236e
Create Date: 2024-06-13 23:54:19.800407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3733b7119f7c'
down_revision = 'af6c7295236e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_producao', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('product', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('roteiro_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roteiro_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'access_point', ['roteiro_id'], ['id'])

    with op.batch_alter_table('ordem_producao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))

    # ### end Alembic commands ###
