"""Initial migration.

Revision ID: 43563b6719e0
Revises: 1196fb77f47c
Create Date: 2024-06-12 16:58:50.860531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43563b6719e0'
down_revision = '1196fb77f47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
