"""empty message

Revision ID: 5d8b0a5ba965
Revises: 
Create Date: 2024-04-09 16:11:29.018368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8b0a5ba965'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('a_fazer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_serial_number_constraint', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('serial_number', ['unique_serial_number_constraint'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('a_fazer', schema=None) as batch_op:
        batch_op.drop_constraint('serial_number', type_='unique')
        batch_op.drop_column('unique_serial_number_constraint')

    # ### end Alembic commands ###
