"""Add traceSerial table

Revision ID: 5f903c4ed258
Revises: c56410251f91
Create Date: 2024-06-14 08:38:42.269879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f903c4ed258'
down_revision = 'c56410251f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trace_serial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=50), nullable=False),
    sa.Column('date_done', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('access_point', sa.String(length=100), nullable=False),
    sa.Column('user', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trace_serial')
    # ### end Alembic commands ###
