"""debugStatus

Revision ID: 75830d07f228
Revises: 3733b7119f7c
Create Date: 2024-06-13 23:56:15.097192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75830d07f228'
down_revision = '3733b7119f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_producao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.INTEGER(), nullable=False, server_default='1'))

    with op.batch_alter_table('product', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('roteiro_id')

    # Atualizar as linhas existentes para garantir que tenham o valor padrão de 1
    op.execute('UPDATE ordem_producao SET status = 1 WHERE status IS NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roteiro_id', sa.INTEGER(), nullable=True))

        # batch_op.create_foreign_key(None, 'access_point', ['roteiro_id'], ['id'])
    with op.batch_alter_table('ordem_producao', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.create_table('_alembic_tmp_ordem_producao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('produto_id', sa.INTEGER(), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=False),
    sa.Column('data_prevista', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
