"""empty message

Revision ID: 81fb0a36161a
Revises: 5b8a988958a8
Create Date: 2024-06-13 13:18:33.150192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81fb0a36161a'
down_revision = '5b8a988958a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordem_producao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_prevista', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['product.id'], name='fk_ordem_producao_produto_id'),  # Specify the name for the foreign key constraint
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_roteiro_id', type_='foreignkey')  # Specify the name of the constraint to drop
        batch_op.drop_column('roteiro_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roteiro_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_product_roteiro_id', 'access_point', ['roteiro_id'], ['id'])  # Specify the name for the foreign key constraint

    op.drop_table('ordem_producao')
    # ### end Alembic commands ###
