"""Create product table

Revision ID: 835dd7c195a6
Revises: 910fd7792517
Create Date: 2024-06-13 09:53:12.681318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835dd7c195a6'
down_revision = '910fd7792517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ultima_producao', sa.DateTime(), nullable=True),
    sa.Column('roteiro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roteiro_id'], ['access_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
