"""create access_point table

Revision ID: 910fd7792517
Revises: 43563b6719e0
Create Date: 2024-06-13 09:18:23.739778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910fd7792517'
down_revision = '43563b6719e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_point')
    # ### end Alembic commands ###
