"""empty message

Revision ID: 9e02c38ec2d5
Revises: d48d1e958c27
Create Date: 2024-07-26 12:56:21.923396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e02c38ec2d5'
down_revision = 'd48d1e958c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trace_serial', schema=None) as batch_op:
        batch_op.alter_column('ordem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'ordem_producao', ['ordem_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trace_serial', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('ordem_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
