"""empty message

Revision ID: af6c7295236e
Revises: ebbb69f15c91
Create Date: 2024-06-13 23:37:50.239983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6c7295236e'
down_revision = 'ebbb69f15c91'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('roteiro_id')
        op.add_column('ordem_producao', sa.Column('status', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roteiro_id', sa.INTEGER(), nullable=True))
        # batch_op.create_foreign_key(None, 'access_point', ['roteiro_id'], ['id'])
        op.drop_column('ordem_producao', 'status')
    # ### end Alembic commands ###
