"""empty message

Revision ID: ebbb69f15c91
Revises: 12085c554a0c
Create Date: 2024-06-13 23:34:28.371285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbb69f15c91'
down_revision = '12085c554a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_producao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('roteiro_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roteiro_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'access_point', ['roteiro_id'], ['id'])

    with op.batch_alter_table('ordem_producao', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
