"""testeStatus

Revision ID: fd7466b230b1
Revises: 75830d07f228
Create Date: 2024-06-13 23:59:18.742607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7466b230b1'
down_revision = '75830d07f228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_producao', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_producao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))

    # ### end Alembic commands ###
